local opt = vim.opt

opt.tabstop = 4
opt.shiftwidth = 4
opt.softtabstop = 4
opt.expandtab = true
opt.smartindent = true
opt.wrap = false
opt.termguicolors = true
opt.number = true
opt.relativenumber = true
opt.foldexpr = 'nvim_treesitter#foldexpr()'
opt.foldmethod = 'indent'
opt.foldlevel = 99
opt.colorcolumn = '99'
opt.textwidth = 99
opt.formatoptions = 't'
opt.undofile = true
opt.linebreak = true
